services:
  api:
    volumes:
      - ./src:/app/src:cached
      - ./api:/app/api:cached
      - ./tools:/app/tools:cached
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
      - LOG_LEVEL=debug
    command: "/app/.venv/bin/python -m uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"

# Note: This file is automatically used in development with `docker compose up`
# and should not be included in production images. Mounting ./src allows
# iterating on the Python package without rebuilding the image.