groups:
  - name: cerverus.rules
    rules:
      - alert: HighErrorRate
        expr: job:request_errors:rate5m > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
